### ISSUE TITLE
Game Window Border/Borderless

### ISSUE THREAD

**Issue by KalinuxYT** [KalinuxYT/FNAF-Restructured#8]
Currently regardless of whether the display mode selected is borderless or not there is no window border displayed.
![Issue1](https://github.com/user-attachments/assets/652d686d-afee-4482-9407-8d008587b73f)

Additionally, at different resolutions the view is not scaled properly causing cutoff.
![Issue2](https://github.com/user-attachments/assets/54cde4e5-44b9-4e3b-aa9f-58a350249ed0)

Additionally, when the user has selected Fullscreen or Borderless Fullscreen should the resolution be automatically detected and selected?

**Comment by HeDeAnTheonlyone** [comment]
If I'm not wrong, I have already fixed all of this with my last commit.

**Comment by KalinuxYT** [comment]
The latest code still contains the issue, at 1280 x 720 cutoff is occurring still.

**Comment by HeDeAnTheonlyone** [comment]
It should auto scale for any Resolution now.
Can yoh show an image?

**Comment by KalinuxYT** [comment]
Will be removing options "Borderless Window" and "Borderless Fullscreen", also will be using "expand" for aspect setting
