### ISSUE TITLE
Launch Splash

### ISSUE THREAD

**Issue by KalinuxYT** [KalinuxYT/FNAF-Restructured#9]
On launch the default Godot game engine splash is briefly shown, we should aim to modify this so only our splash is shown.

**Comment by HeDeAnTheonlyone** [comment]
We can disable the default splash screen in the settings

**Comment by KalinuxYT** [comment]
Do we want to modify it in any way or just not have any image display on initial load?

**Comment by HeDeAnTheonlyone** [comment]
We have our own splash screen. We don't need the default one.

**Comment by KalinuxYT** [comment]
This has been resolved
